stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $MASTER_SSH_KEY
    - apk update && apk add openssh-client
    - ssh -i $MASTER_SSH_KEY -o StrictHostKeyChecking=no $MASTER_SSH_USER@$MASTER_HOST "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $MASTER_SSH_KEY -o StrictHostKeyChecking=no $MASTER_SSH_USER@$MASTER_HOST "docker pull $TAG_COMMIT"
    - ssh -i $MASTER_SSH_KEY -o StrictHostKeyChecking=no $MASTER_SSH_USER@$MASTER_HOST "docker container rm -f my-app || true"
    - ssh -i $MASTER_SSH_KEY -o StrictHostKeyChecking=no $MASTER_SSH_USER@$MASTER_HOST "docker run -d -p 3000:3000 --name my-app $TAG_COMMIT"
  environment:
    name: production
    url: http://your_MASTER_HOST
  only:
    - master